addons:
  browserstack:
    username: "klaushartl1"
    access_key:
      secure: "c5aqwPGpsY+EQw4BLZY3tdRVQjUglGSzhVEfC98jjw5l8M6nm4dFIs4p36Nidc0KSfjiws+VUWc+rW53AjtbG/C0b67hKwFWfnfV/Tacan2NbrR7Hsgdx0wpC4YSZv+prYjfbXIdncReITsxBf27lysAHzmTkx76+AZtgUBTNK8="
language: node_js
node_js:
  - '6'
  - '8'
  - '10'
cache:
  directories:
    - node_modules
stages:
  - test
  - name: browserstack
    if: env(BROWSERSTACK_USERNAME) IS present
jobs:
  include:
    - stage: browserstack
      node_js: '10'
      script: grunt exec:browserstack-runner
